import time, random
print("You wake up to the sounds of birds chirping. You look around. A second ago you remember laying in your bed.")
time.sleep(6)
print("A stickynote lands on your nose it says:")
time.sleep(4)
print("You have appeared in another world in order to leave you must learn how to live along side the villagers. At some point you will earn the key to leave this world and come back to earth intil you come back, earth's time is puased.")
time.sleep(10)
print("You see a village in the distance. What do you do?")
time.sleep(4)
print("1, RUN")
time.sleep(1)
print("2, Go to the village")
answer = input()

if answer == "1":
    print(random.choice(["You run off the edge of the unknown world.Nice try better luck next time!","You run strait into a statue there is a hole right in front of it and you fall in. Nice try better luck next time!","Some how against all logic a dragon grabs you and it flighs you home.Good job you win!"]))

if answer == "2":
    print("You start running to the village your belly grumbles you deside that you will grab some food once you get there.")
    time.sleep(5)
    print("You see a bank you also see a small bakery. What do you do?")
    print("1, Go to the bank")
    print("2, Go to the backery")

    answer = input()

    if answer == "1":
        print("The person at the bank tells you that she will give you some money and maybe alot becuase your new hear.")
        time.sleep(4)
        print("She gives you")
        time.sleep(2)
        print(random.choice(["$5","$2","$1","$10","$20","$30"]))
        print("She says in order to earn more money you will need to work for money.")

if answer == "2":
    print("You eneter the backery and in it you see the yummiest cookie you have ever seen you ask the person sitting in front of something that looks like a treasure chest if you can have the cookie. ")
    time.sleep(7)
    print(random.choice(["He gives you a cookie because you'r new but he says that next time he will not let you get a cookie for free then he calls the bank person and she gives you $10 and she says in order to earn more money you must work", "The store person says that you need money in order to buy a cookie and then he offers to call the bank person for money when he calls, the bank person gives you $5 and says that you can earn more money buy working."]))
    time.sleep(6)
print("You deside to go find a place to work at because you need money so you can build a house.")
time.sleep(4)
print(random.choice(["It's geting dark you have to hurry!", "It's the middle of the day you can take your time!", "It's early in the morning there is no need to hurry!"]))
time.sleep(3)
print("You step outside and look around you see three other buildings that you didn't notice before. There's a small shop that looks like some sort of s.t.e.m store amd two other stores one that looks like a resturant and another that looks like a construction center.")
time.sleep(7)
print("What do you do?")
time.sleep(2)
print("1, Go to the s.t.e.m store.")
time.sleep(3)
print("2, Go to the resturant.")
time.sleep(3)
print("3, Go to the construction center.")

answer = input()

if answer == "1":
    print("You go inside the s.t.e.m store. There are so many types of elechronics that you have never seen before.")
    time.sleep(3)
    print("A villager at the front of the room clears his throat. You turn around to face the man. You tell him that you are looking for a job.")
    print(random.choice(["He says that he can pay you $50 a day if you can orginize the electronics and redstone.","He says he will pay you $100 a day if you work at the front desk."]))
    time.sleep(3)
    print("The bell at the front of the door rings and another villager walks in. The villager you were talking to gets distracted and starts talking to the new customer.")
    time.sleep(3)
    print("Another villager that seems to also work at the s.t.e.m store walks up to you and asks what the boss said your job is. He tells you to say the exact same thing that the boss said to you except use I and me.")
    time.sleep(4)
    answer = input()

    if answer == "He says that he would pay me $100 a day if I work at the front desk.":
        time.sleep(1)
        print("The villager shose you the cash resture and a look of suprise crosses his face when you tell him that you have no idea what this thing is.")
        time.sleep(2)
        print("He tells you just click the button on the cash resture and it will open and you can put the emeralds inside.")
        time.sleep(3)
        print("He says if you need any help with anything just ask.")
        time.sleep(3)
        print("As you wait you look around.")
        time.sleep(2)
        print("You had just started looking at the so called Ender chests when...")
        time.sleep(2)
        print(random.choice(["A man wereing a frown and a mustache walks in and yells at the top of his lungs that he wants an ender chest.","A little girl and her dad walk in both of them are smiling they ask you for a few railroad tracks and materials.","A little boy and girl walk in asking for a pack of redstone."]))
        time.sleep(4)
        print("What do you do?")
        time.sleep(0.5)
        print("1.Give them a pack of redstone for 3 emeralds")
        time.sleep(1)
        print("2.Give them an enderchest for 5 emeralds")
        time.sleep(1)
        print("3.Give them railroad tracks and materials for 8 emeralds")
        answer=input()
        if answer == "1":
            print("You give them a pack of redstone for 3 emeralds.Good job on your first sail!")
            time.sleep(2)
            print("The boss comes back and gives you $100 and congratulates you on your first sail!")
            time.sleep(2)
            print("Then you deside to go to the cunstruction center.")
            time.sleep(1)
            print("The person at the construction center asks you wether you want him to build your house or if you'd like to build it your self.")
            time.sleep(2)
            print("1.Build your house your self")
            time.sleep(1)
            print("2.Ask them to build it for you")
            answer=input()
            if answer == "1":
                print("You tell him that you want to build it your self.")
                time.sleep(2)
                print("He gives you bricks stones and all the other things you need to build it yourself.")
                time.sleep(2)
                print("1.You deside to build your house modern")
                time.sleep(1)
                print("2.You deside to build your house homey")
                answer=input()
                if answer == "1":
                    print("You start building as fast as you can your modern house looks ok but it is a little uneven on some parts.")
                    time.sleep(3)
                    print("Your tired so deside to go to sleep your house shake a little bit when you climb in bed you remember that now you only have 10 emeralds left.")
                    time.sleep(4)
                    print("The next morning you wake up under your house it turned out that during the night your house fell down!")
                    time.sleep(2)
                    print("Nice try!")
                if answer == "2":
                    print("You build your house homey it looks ok but it feels like it may fall down at any second yor house almost falls when you lay down in bed you remember that you only have 5 emeralds left.")
                    time.sleep(5)
                    print("Next morning you wake up under your house it turns out that last night your house fell!")
                    time.sleep(2)
                    print("Nice try!")
            if answer == "2":
                print("You tell him that you want them to build it for you he says that he will build you a modern house for 100 emeralds but it would not be to modern but still pretty modern.")
                time.sleep(5)
                print("They build you a perfect house just how you thought it would be.")
                time.sleep(3)
                print("You thank the construction team for there hard work and pay them the 100 emeralds.")
                time.sleep(3)
                print("You go to bed in your amazing house.")
                time.sleep(2)
                print("When you wake up your laying in your bed in your house.")
                print("Good job you won!☺☺☺☺☺")
        if answer == "2":
            print("You give them the ender chest for 5 emeralds.Congratulations on your first sail!")
            time.sleep(1)
            print("As they leave they tell you that the cunstruction center heard about you being ew to the village and desided to build a house for you.")
            time.sleep(3)
            print("The boss comes over and pays you 100 emeralds and says good job on your first sail!")
            time.sleep(3)
            print("You go to the place where thay built your house they ask you to pay them 100 emeralds for the house.")
            time.sleep(3)
            print("1.Run and not pay the construction team")
            time.sleep(1)
            print("2.Pay the construction team 100 emeralds.")
            answer=input()
            if answer == "1":
                print("The police chases you down and locks you up in prison.")
                time.sleep(2)
                print("There's probably no chance in excaping now.Nice try!")
            if answer == "2":
                print("You pay the construction team 100 emeralds.")
                time.sleep(2)
                print("You lay down in your bed you feel that your house is amazing.")
                time.sleep(2)
                print("The next morning you wake up in your bed in your house!Good job you won!🧐")
        if answer == "3":
            print("You give them the rail road tracks and other rail road materials.Good job on your first sail!")
            time.sleep(3)
            print("Just as soon as you have finished your first sail the boss comes over and pays 100 emeralds and tells good job.")
            time.sleep(3)
            print("Right before they leave thay inform you that they work at the construction center and they can build you a homey house for 100 emeralds.")
            time.sleep(3)
            print("Do you say yes or no?")
            time.sleep(1)
            print("1.No")
            time.sleep(0.5)
            print("2.Yes")
            answer=input()
            if answer == "1":
                print("They leave and it gets dark you go out side and start looking for some place to sleep for the night when an enderman runs up to you and kills you.")
                time.sleep(4)
                print("Nice try!")
            if answer == "2":
                print("You tell them yes they build you a great homey house.")
                time.sleep(2)
                print("You thank them the house and pay them 100 emeralds.")
                time.sleep(2)
                print("You lay down in bed and fall asleep almost immediatly.")
                time.sleep(2)
                print("You wake up the next morning in your house in your bed!")
                time.sleep(2)
                print("Good job you won!🙂")
    if answer == "He says he can pay me $50 a day if I can orginize the electronics and redstone":
        print("The villager shose you the storage room where you will be sorting things.")
        time.sleep(2)
        print("He says just sort things in groups of what they are.He tells you if you get one thing wrong you will get in big trouble.")
        time.sleep(1)
        print("Well if you want to get enough money for a house you will need to start working.")
        time.sleep(2)
        print("You see 2 rail road tracks. What do you do?")
        time.sleep(1)
        print("1.Put them in a box labeled rail road tracks")
        time.sleep(1)
        print("2.Put them in a box labeled redstone.")
        time.sleep(2)
        answer = input()
        if answer == "1":
            print("You put the railroad tracks in the box labeled railroad tracks you continue working and sorting untill the boss comes in and congratulates you on your hard work.")
            time.sleep(3)
            print("He tells you to go to the contruction center and ask them to build you a modern tree house for 50 emeralds.")
            time.sleep(2)
            print("You deside to go to the contruction center.")
            time.sleep(1)
            print("When you get there it turns out that they are already ready for you.")
            time.sleep(1)
            print("They build you an amazing modern treehouse.")
            time.sleep(1)
            print("You thank them for there hard work and pay them 50 emeralds.")
            time.sleep(2)
            print("Your treehouse is so comfertable that as soon as you lay in bed, you fall fast asleep!")
            time.sleep(2)
            print("The next morning you wake up in your house in your bed! Good job you won!😃")
        if answer == "2":
            print("A siran goes off the police run in and arest you for making a mistake in your very important job!")
            time.sleep(2)
            print("Theres probably no chance in excaping.Nice try!")
if answer == "2":
    print("You walk inside the resturaunt you tell the girl at the front desk that your looking for a job.")
    time.sleep(3)
    print("She says she will pay you $70 a day if you work at the front desk.")
    time.sleep(2)
    print("She gives you no choice but to say yes.")
    time.sleep(1)
    print("She tells you to just give them a table when they walk in and that that ender chest over right next to you will tell you wich table are open.")
    time.sleep(3)
    print("The first person walks in. What do you do?.")
    time.sleep(1)
    print("The ender chest shose a red mark on table 10 and a green mark on table 4.")
    print("1.You give them table 10")
    time.sleep(1)
    print("2.You give them table 4")
    answer = input()
    if answer == "1":
        print("You deside to give them table 10.")
        time.sleep(1)
        print("The girl you saw earlyer at the front desk comes running mader then ever she tells you that table 10 was not ready yet then she fires you!")
        time.sleep(3)
        print("You just start looking for another job when a enderman walks up to you and kills you.")
        time.sleep(3)
        print("Nice try!")
    if answer == "2":
        print("You send them to table 4.")
        time.sleep(1)
        print("You keep working untill the girl comes and pays you 70 emeralds.")
        time.sleep(3)
        print("After that you go to the construction center hoping that you have enough money to pay them for a proper house.")
        time.sleep(4)
        print("They tell you that they are out of materials for a modern house but the can build you a homey one.")
        time.sleep(3)
        print("They give you no choice but to say yes.")
        time.sleep(2)
        print("They build you your house and when you climb in bed after thanking them and paying them 70 emeralds, you think about living in this village.")
        time.sleep(4.5)
        print("The next morning you wake up in your own bed in your own house! Good job you won!😛")
if answer == "3":
    print("You walk inside the construction center the man at the front of the door asks you what you want.")
    time.sleep(3)
    print("1.You tell him that you want a job")
    time.sleep(1)
    print("2.You tell him you want a house")
    answer=input()
    if answer == "1":
        print("You tell him you want a job.")
        time.sleep(1)
        print("He tells you that you can help them draw out houses for $80.")
        time.sleep(2)
        print("What do you do?")
        time.sleep(1)
        print("1.Say no")
        time.sleep(1)
        print("2.Say yes")
        answer=input()
        if answer == "1":
            print("You tell him no he says that there are no other open jobs so you deside to leave.")
            time.sleep(2)
            print("As you start looking for another job you are so deep in thought that you don't notice the enderman standing right in front of you it kills you.Nice try!")
        if answer == "2":
            print("He gives you a book and quill and tells you to draw any house you want.")
            time.sleep(3)
            print("What do you want to draw?")
            time.sleep(1)
            print("1.A modern under water house")
            time.sleep(1)
            print("2.A homey tree house")
            answer=input()
            if answer == "1":
                print("You draw a modern under water house you draw and draw untill you really feel like you want this house.")
                time.sleep(4)
                print("The boss comes over and pays you 80 emeralds you ask him if you can have the house you drew he says they can build you it for you for 80 emeralds.")
                time.sleep(4)
                print("The construction team builds you your under water modern house you thank them for their hard work and pay them 80 emeralds.")
                time.sleep(4)
                print("As you lay in bed you fall asleep almost ameaditly because of the sound of water bubbling outside your house.")
                time.sleep(4)
                print("You wake up in a sharks mouth the shark must have burst in while you where sleeping maybe an under water modern house wasn't such a good idea after all. Nice try!")
            if answer == "2":
                print("You deside to draw a homey tree house when your finished you love it so much that when the boss comes over and pays you 80 emeralds you ask him if they can build the house.")
                time.sleep(5)
                print("He says yes and the construction team builds the homey tree house for you.")
                time.sleep(3)
                print("After they build you a house you thank them for there work they ask you for payment.")
                time.sleep(3)
                print("What do you do?")
                time.sleep(1.5)
                print("1.Pay them nothing")
                time.sleep(1)
                print("2.Pay them 80 emeralds")
                answer=input()
                if answer == "1":
                    print("You say that you don't want to pay them anything they get mad at you and the police catch you and lock you up.")
                    time.sleep(3)
                    print("There's probably no chance in excaping now. Nice try!")
                if answer == "2":
                    print("You pay them 80 emeralds then you climb into your tree house and go to sleep.")
                    time.sleep(3)
                    print("The next morning you wake up in your own tree house in your own bed.Good job you won!🙃")
    if answer == "2":
        print("He tells you that you need money if you want them to build a hous for you.")
        time.sleep(2)
        print("1.Ask really nicely for them to build you a house")
        time.sleep(2)
        print("2.Ask for a job")
        answer=input()
        if answer == "1":
            print("He gets really mad and throws you out of the construction center then an enderman finds you and kills you. Nice try!")                      
        if answer == "2":
            print("He hands you a book and quill and tells you to draw a modern tree house.")
            time.sleep(3)
            print("You do what your told then he comes over and pays you 80 emeralds he asks you if you want them to build you this tree house for 80 emeralds.")
            time.sleep(4)
            print("What do you do?")
            time.sleep(1)
            print("1.You say yes")
            time.sleep(1)
            print("2.You say no")
            answer=input()
            if answer == "1":
                print("You say yes they build your house untill there's only a little bit left to finish when a storm comes along. What do you do?")
                time.sleep(3)
                print("1.Tell them to quickly finish up and then they can come inside the tree house wich is on a high tree but not nearly as high as the rest of the things sarounding it.")
                time.sleep(4)
                print("2.Tell them to go and seek shelter although the tree house is not finished")
                answer=input()
                if answer == "1":
                    print("You tell them to quickly finish up and then seek shelter in your tree house.")
                    time.sleep(3)
                    print("They agree and quickly finish they come inside with you untill the storm is over.")
                    time.sleep(3)
                    print("When they leave you are so tired that you quickly fall asleep.")
                    time.sleep(3)
                    print("When you wake up the next morning you are in your own house in your own bed.Good job you won!😀")
                if answer == "2":
                    print("You tell them to stop building and go seek shelter although the tree house is not finished.")
                    time.sleep(3)
                    print("They agree wants they all left you go inside your unfinished tree house.")
                    time.sleep(3)
                    print("You fall fast asleep on the floor of your tree house when you wake up your under a pile of rubble that used to be the tree house.")
                    time.sleep(4)
                    print("It turned out that last night the storm nocked down your tree house because it as not finished so it was unstable.")
                    time.sleep(4)
                    print("Nice try!")
            if answer == 2:
                print("You say that you don't want the tree house.")
                time.sleep(2)
                print("They deside to build you homey brick house instead.")
                time.sleep(2)
                print("They build it so quickly that by the time that they're finished the storm that was ment to come came and they could go strait home because it was done.")
                time.sleep(3)
                print("They built the house so strong that when you go to bed the pitter patter of the rain helps you go to sleep.")
                time.sleep(3)
                print("When you wake up your in your house in your bed! Good job you won!😎")
